package config

// keyDescriptions is the one-line operator description of every canonical
// settings key: rendered under the key in the settings UI and part of the
// fuzzy-search corpus (key, description, value). One entry per registry key,
// in registry order; completeness is enforced at first registry use
// (keyInfos panics on a missing entry) and pinned both ways by
// TestKeyDescriptionsComplete.
var keyDescriptions = map[string]string{ //nolint:gosec // G101-Fehlalarm: Schlüssel wie "…api_key"/"…db_password" sind REGISTRY-NAMEN mit englischen Beschreibungstexten, keine Credential-Werte — die Werte-Seite der Map ist reine Doku-Prosa.
	"server.db":                                      "Name of the PostgreSQL database the daemon connects to; changing it requires a process restart",
	"server.db_user":                                 "PostgreSQL role used for the store's database connection; applied only on restart",
	"server.db_password":                             "Password for the database role; treated as a secret (only presence is shown) and applied on restart",
	"server.db_host":                                 "Hostname or IP of the PostgreSQL server to connect to; applied on restart",
	"server.db_port":                                 "TCP port of the PostgreSQL server; a malformed value aborts boot, changes apply on restart",
	"server.db_sslmode":                              "libpq sslmode for the database connection (disable, require, verify-full, ...); applied on restart",
	"server.listen_addr":                             "host:port the HTTP API binds to, e.g. :8080; applied on restart",
	"server.instance_kind":                           "What this instance is: live (default) or measure-copy — a corpus restored for the shadow measurement programme; the armsweep driver refuses shadow_types against anything but measure-copy, applied on restart",
	"dream.enabled":                                  "Master switch for the background dream pipeline (link discovery, keywords, temporal review); takes effect on restart",
	"dream.idle_wait":                                "Seconds the dream scheduler sleeps when no block is eligible; eligible blocks are still processed back-to-back",
	"dream.parallelism":                              "Number of concurrent dream workers (clamped to 1-16, restart required); higher values load the chat backend harder",
	"dream.language":                                 "Language tag for the daily-synthesis report; empty or de keeps the legacy German Tagesbericht series, other tags localize title and prompt",
	"dream.json_mode":                                "Wire policy of the four parsing dream stages: strict sends the backend's JSON mode, off sends plain chat and leaves the local parsers as the only validator; the prose daily report never uses JSON mode",
	"dream.link_floor_confidence":                    "Confidence [0,1] assigned to LLM links returned without a strength signal; default 0.9 keeps them above the graph-expansion retrieval gate",
	"dream.temporal_timeout":                         "Seconds allowed for the temporal Phase-2 LLM review; a timeouts.dream override on the serving backend row takes precedence",
	"dream.cycle_timeout":                            "Seconds one whole dream cycle (pick, temporal, keywords, RRF, eval, recurrence) may run; the outer ceiling a timeouts.dream row can only shorten",
	"dream.num_predict":                              "Output-token cap of the dream link-evaluation and recurrence-confirm calls; 0 = the built-in default, a model_map param on the row wins",
	"dream.eval_cap_retry_factor":                    "Scales the output cap of one retry after a dream link evaluation hit the cap; 1 or less disables the retry, a second hit books the block inert",
	"dream.backoff_mode":                             "Curve shaping how the re-dream interval grows with a block's eval count: exp, log, linear, or off (fixed active/inert cooldown days)",
	"dream.backoff_factor":                           "Curve steepness: growth base for exp, log coefficient, or days-per-step slope for linear; higher cools mature blocks off faster",
	"dream.backoff_grace":                            "Free eval cycles before the back-off curve starts growing; 0 grows from the very first dream",
	"dream.backoff_cap":                              "Ceiling on the re-dream cooldown (duration, e.g. 45d); back-off only delays re-dreams, no block waits longer than this",
	"dream.backoff_min":                              "Cooldown floor at eval count 0 (duration, e.g. 12h); fresh blocks re-dream after roughly this interval to catch new links early",
	"dream.backoff_inert_offset":                     "Extra curve steps applied when a cycle finds no links, so inert blocks start further up the same cooldown curve",
	"rerank.enabled":                                 "Turns the post-retrieval rerank stage on or off; off keeps the RRF fusion order as the final ranking",
	"rerank.max_docs":                                "How many top candidates are sent to the cross-encoder for rescoring; 0 or less falls back to 50",
	"rerank.blend_weight":                            "Cross-encoder share of the blended score in [0,1]; 1.0 lets the reranker fully decide the final ranking over the RRF order",
	"graph.enabled":                                  "Master switch for the post-RRF dream-graph expansion stage; off leaves query results byte-identical to plain RRF",
	"graph.directed":                                 "When true only outbound dream links are traversed; false also follows inbound edges, treating the link graph as undirected",
	"graph.hop_depth":                                "Number of traversal hops from each seed; hops beyond 1 decay by an extra boost_weight factor per hop, with a visited-set against loops",
	"graph.seed_count":                               "How many top RRF results seed the graph expansion; more seeds widen the neighbor pool at extra edge-fetch cost",
	"graph.seed_score_floor":                         "Fraction of the top hit's RRF score a result must reach to act as an expansion seed; keeps weak tail results from seeding the graph",
	"graph.per_seed_cap":                             "Maximum neighbors kept per seed, highest raw confidence first; limits per-seed fan-out during expansion",
	"graph.max_injected":                             "Global cap on newly appended graph-only neighbors per query, highest endorsement kept; reinforcing existing hits is not counted",
	"graph.min_confidence":                           "Minimum dream-link raw_confidence for non-recurrent edges to be traversed; raising it keeps only stronger links",
	"graph.min_confidence_recurrent":                 "Minimum raw_confidence for recurrent edges, gated separately and higher since recurrent links sit near 0.96 in practice",
	"graph.boost_weight":                             "Master strength of the graph contribution: scales the score boost of existing hits, new-neighbor scores, and the per-hop decay",
	"graph.hub_damping":                              "When true a neighbor's injection is divided by sqrt of its inbound degree so high-degree hub blocks cannot dominate the boost",
	"graph.weight_topical":                           "Per-edge boost weight for topical links; kept lowest by default because topical is the most common type and its confidence gate barely thins it",
	"graph.weight_factual":                           "Per-edge boost weight for factual links during expansion; higher values let factual neighbors score stronger",
	"graph.weight_causal":                            "Per-edge boost weight for causal links during expansion; higher values let causal neighbors score stronger",
	"graph.weight_recurrent":                         "Per-edge boost weight for recurrent links during expansion; the strongest type at the default 1.0",
	"graph.new_placement_frac":                       "Fraction of the top hit's score at which a newly injected neighbor is placed, scaled by endorsement; keeps it inside the reranker window",
	"graph_overview.enabled":                         "Master switch for the topic-map overview: gates both the scheduled Louvain supergraph rebuild and its read endpoint",
	"graph_overview.rebuild_interval":                "Seconds between scheduled overview rebuilds (default 6h); shorter keeps the topic map fresher at recurring compute cost",
	"graph_overview.resolution":                      "Louvain resolution parameter for topic clustering; above 1.0 yields more, smaller clusters, below 1.0 fewer, larger ones (<=0 falls back to 1.0)",
	"graph_overview.max_nodes":                       "Liveness guard for the gonum engine: a rebuild is skipped when the node count exceeds this (Louvain stalls past ~200k); 0 = uncapped",
	"graph_overview.rebuild_timeout":                 "Seconds one rebuild run may take before it is abandoned to keep the scheduler loop alive; 0 falls back to 900",
	"graph_overview.tombstone_retention":             "Seconds a retired topic keeps its core blocks available for re-attach, letting rebuilds revive old topic identities; 0 disables re-attach",
	"graph_overview.run_retention":                   "Seconds of rebuild-run journal history kept before purge; 0 retains every row forever as a deliberate forensic choice",
	"graph_overview.csr_loader":                      "Switches rebuild input loading to the two-pass CSR cursor build, cutting peak memory (~423 MB at the 200k cap) versus the rawEdge path",
	"graph_overview.engine":                          "Community-detection engine for the rebuild, gonum or ctx; switching recomputes every cluster_id — a one-time global partition break",
	"graph_overview.time_budget":                     "Seconds the compute phase may run under engine=ctx before a clean abort between queue blocks (load time excluded); 0 = no budget",
	"graph_overview.max_nodes_ctx":                   "Node-count emergency stop applied when engine=ctx (gonum uses max_nodes instead); the effective cap is journaled as max_nodes_eff",
	"graph_overview.refine":                          "Enables the Leiden refinement pass under engine=ctx so every delivered community is connected; off risks disconnected topics",
	"graph_overview.delta_persist":                   "Writes only changed member rows instead of delete-all plus insert-all; result-identical but avoids massive dead-tuple vacuum pressure",
	"graph_overview.component_split":                 "Enables the connected-component pre-pass with per-component gamma rescaling under engine=ctx; provably objective-identical clustering",
	"graph_overview.worker_mem_limit":                "Go heap cap in bytes for the rebuild child process; 0 = off — tune against peak_rss_kb in the run journal, too low aborts every run",
	"graph_overview.label_enabled":                   "Enables LLM naming of topics; when off (or below label_min_topics) the deterministic fallback still labels every topic",
	"graph_overview.label_interval":                  "Seconds between label-arm ticks, deliberately decoupled from the rebuild cadence so labels track core drift and backlogs drain",
	"graph_overview.label_batch":                     "Maximum topics labelled per tick across all scopes of the served tenant; first defense layer against the cold-start labelling storm",
	"graph_overview.label_min_topics":                "Minimum living topics a scope needs before LLM labelling runs at all; below it no LLM call is made and the fallback names carry the map",
	"graph_overview.label_prompt_max_titles":         "Maximum core-block titles included in one labelling prompt; a token-budget resource bound (~24 titles is roughly 600-800 tokens)",
	"graph_overview.label_credentials_fallback_only": "When on, topics with a credentials core skip the LLM entirely and keep their deterministic fallback name; stage 3 of label hardening",
	"graph_overview.label_timeout":                   "Seconds one topic label may spend in total, dispatch queue wait included; a timeouts.digest row bounds only the wire call and is clamped by this",
	"root_map.enabled":                               "Master gate for the root-map background job; while off the scheduler's map production returns before its first query",
	"root_map.budget_bytes":                          "Byte ceiling for the rendered root map; the renderer measures and stops at it, and values above the 50 KB block write cap are refused",
	"root_map.small_cluster_max":                     "Cluster size at or below which clusters are only counted in one collector line instead of rendered as individual topics",
	"root_map.footer_reserve_bytes":                  "Bytes the measuring loop keeps free for the map's two accounting footer lines; rendering errors rather than truncating them",
	"root_map.count_timeout":                         "Seconds allowed for the coverage counts, the map's only corpus-sized step; on expiry the map omits the denominator instead of estimating",
	"root_map.label_budget":                          "Cap on LLM label requests per map cycle; 0 ties it to the rendered row budget so labels are produced only for rows the map shows",
	"root_map.super_enabled":                         "Enables the meta-cluster level: a second Louvain pass over the cluster supergraph rendered as a coarse section of the root map",
	"root_map.super_min_resolution":                  "Lower bound of the Louvain resolution (gamma) search for meta-clusters; smaller values permit fewer, larger super-communities",
	"root_map.super_max_nodes":                       "Per-scope cap on cluster supergraph nodes for the meta level; scopes above it skip the second Louvain and fall back to the flat list",
	"cluster.enabled":                                "Master switch for the query-time boost stage that up-ranks results sharing a Louvain cluster with the query's strong hits",
	"cluster.seed_count":                             "Number of top-ranked results that vote on the query's clusters; more seeds broaden the vote but dilute each cluster's share",
	"cluster.top_clusters":                           "Maximum number of winning clusters whose members receive the boost; qualifying clusters beyond this are dropped",
	"cluster.min_share":                              "Minimum damped vote share a cluster needs to qualify as a winner; raising it makes boosting stricter and rarer",
	"cluster.boost_weight":                           "Master boost strength: RRF scores are multiplied by 1+weight×share, so this bounds the maximum uplift a cluster hit can give",
	"cluster.size_damping":                           "Normalises a cluster's vote share by its share of the corpus so mega clusters cannot win nearly every query by size alone",
	"cluster.centroid_enabled":                       "Enables the query-independent centroid arm that locates the query among cluster centroids even when seed results are unusable",
	"cluster.centroid_weight":                        "Blend factor fusing centroid-probe shares with seed-vote shares (0 = seeds only, 1 = centroids only)",
	"cluster.centroid_top_k":                         "How many nearest cluster centroids the query-time probe returns; more candidates widen the centroid vote at probe cost",
	"cluster.inject_max":                             "Cap on unseen blocks per winning cluster that may be appended to a result set; 0 disables injection entirely",
	"cluster.max_staleness":                          "Age in seconds past which the cluster stage switches itself off, preventing boosts computed from a frozen cluster map",
	"cluster.ego_annotate":                           "Adds cluster-membership annotation to ego-graph responses via one extra DB probe; probe failures degrade to no annotation, never a 500",
	"cluster.ego_annotate_max_nodes":                 "Node-count ceiling for ego-graph cluster annotation; larger responses return empty annotations plus a budget trip instead of probing",
	"cluster.facet_enabled":                          "Enables the cluster facet on context search, restricting results to members of one cluster given by UUID",
	"cluster.route_enabled":                          "Gates the /api/graph/cluster route; while off (or the graph overview is off) the endpoint answers an indistinguishable 404",
	"cluster.centroid_build":                         "Enables the background centroid build that runs in its own transaction after each cluster-map rebuild commits",
	"cluster.centroid_timeout":                       "Time budget in seconds for one background centroid build run, clamped independently of the rebuild's own timeout",
	"cluster.centroid_batch":                         "Number of topic centroids recomputed per transaction chunk during the background build; smaller chunks shorten lock windows",
	"cluster.centroid_work_mem":                      "PostgreSQL work_mem literal (e.g. 256MB) applied via SET LOCAL to the centroid aggregation statement during the build",
	"cluster.centroid_ann_threshold":                 "Centroid count above which reads build and use an HNSW index; below it an exact scan is cheaper and has no recall question",
	"cluster.centroid_ef_search":                     "hnsw.ef_search applied to the query-time centroid probe; a no-op while the centroid count is below the ANN threshold (exact scan)",
	"graph_cache.enabled":                            "Master gate for the in-process CSR adjacency cache over both link tables; off keeps the rebuild inert and consumers on SQL fallback",
	"graph_cache.rebuild_interval":                   "Seconds for the unconditional cache rebuild measured from the last build start (default 6h); covers missed dirty signals",
	"graph_cache.debounce_window":                    "Seconds a dirty signal must stay quiet before a signal-driven cache rebuild fires; batches bursts of link writes into one rebuild. 0 = rebuild on the next scheduler poll without a quiet requirement (poll-bounded; min_rebuild_interval still brakes)",
	"graph_cache.min_rebuild_interval":               "Minimum seconds since the last build start before another signal-driven rebuild may run; prevents rebuild storms under steady writes",
	"graph_cache.max_pending_age":                    "Seconds after the oldest unconsumed dirty signal by which a rebuild fires regardless of debounce; the starvation bound under dense writes",
	"graph_cache.max_staleness":                      "Seconds of pending dirty age after which the cache degrades and consumers fall back to SQL; bounds the maximum cache lie, idle never degrades",
	"graph_cache.failed_threshold":                   "Consecutive cache-build failures after which the automaton turns Failed, showing red status and logging an error per attempt",
	"graph_cache.degree_walk_budget":                 "Edge-visit cap for the hint-filtered degree walk; past the budget the reported degree becomes a lower bound instead of an exact count",
	"graph_cache.serve_ego":                          "Lets the ego-graph endpoint answer from the CSR cache snapshot instead of SQL; reserved consumer flag, off means SQL path",
	"graph_cache.serve_expand":                       "Lets query-time graph expansion answer from the CSR cache snapshot instead of SQL, with automatic SQL fallback on a stale snapshot",
	"query.score_threshold":                          "Minimum RRF score a retrieved source needs to enter answer synthesis; raising it drops weaker sources from answers",
	"query.confident_threshold":                      "Top-source RRF score required to label an answer confident; below it confidence downgrades to low — must stay above score_threshold",
	"query.semantic_floor":                           "Minimum cosine similarity the best embedding-matched result must reach before a query is worth an LLM call; below it, and with no lexical-only hit carrying the result set, the answer is refused without synthesis. 0 = off",
	"query.prompt_version":                           "Selects the synthesis system prompt generation (v5.2 or v6); values outside these are rejected at config load",
	"query.timezone":                                 "IANA timezone used to interpret temporal queries and render timestamps; empty means UTC",
	"query.rate_limit_write":                         "Maximum write operations per API key in a 60-second window; 0 disables write rate limiting",
	"query.rate_limit_read":                          "Maximum read operations per API key in a 60-second window on search/graph/overview endpoints; 0 (default) disables it",
	"digest.mode":                                    "Linear topic-map build mode: full keeps writing it, stub shrinks it to a pointer at the root map, off stops digest writes entirely",
	"scheduler.read_scopes":                          "Scopes the background pipelines (dream, digest, topic labeling, audit) read blocks from, intersected with actual entitlements",
	"scheduler.home_scope":                           "Scope that background jobs write their derived blocks and classification/audit results into",
	"scheduler.llmlog_retention_days":                "Days before the janitor blanks prompt/response bodies in the LLM log; telemetry rows survive, 0 keeps bodies forever",
	"events.tick_interval":                           "Seconds between status-collector refreshes of the cheap sources; /api/status serves this cache instead of rebuilding per request",
	"events.queue_stats_interval":                    "Seconds between dream-queue depth scans, kept off the base tick because each scan is a full pass over context_blocks",
	"events.ping_interval":                           "Seconds between SSE keepalive pings on /api/events; must stay below the fronting proxy's read timeout or idle streams get dropped",
	"events.max_connections":                         "Cap on concurrent /api/events SSE streams; above it new clients get 429 and degrade to polling",
	"events.db_stats_interval":                       "Seconds between refreshes of the /api/status db section (migrations, extensions, relations, HNSW, embed backlog)",
	"events.llmcall_coalesce_threshold":              "LLM-log rows per tick above which the SSE frame carries a count-only refetch signal instead of the rows themselves",
	"webhook.rate_limit":                             "Signature-valid GitHub deliveries accepted per project in a 60-second window; unsigned floods never reach this counter",
	"webhook.retention":                              "Age (h/d/w/m/y suffix) after which processed webhook deliveries are purged from the inbound queue; 0 keeps them forever",
	"project.events.max_connections":                 "Per-tenant cap on concurrent /api/project/events SSE streams; above it new subscribers are refused",
	"project.events.flush_interval":                  "Seconds domain events accumulate per project before flushing as one frame set, collapsing import bursts to one frame per tick",
	"project.events.ping_interval":                   "Seconds between SSE keepalive pings on the project event stream; keep below the fronting proxy's read timeout",
	"project.events.coalesce_threshold":              "Blocks per project per tick above which the event frame degrades to a count-only issues-bulk refetch signal",
	"project.sync.rate_limit":                        "Manual forge-sync runs allowed per project per hour, shared across all API keys of the project; excess gets 429 with Retry-After",
	"project.sync.max_concurrent":                    "Process-wide cap on simultaneously running forge syncs; the semaphore is sized at boot, so changes require a restart",
	"llmlog.max_limit":                               "Upper bound on the limit parameter of one GET /api/llmlog page, keeping a single read over the telemetry hypertable bounded",
	"webchat.enabled":                                "Gates the web-chat streaming and session API routes; off returns 404 and the web UI hides the chat feature",
	"webchat.max_iterations":                         "Caps tool-call loop iterations per chat turn; after the cap one closing model call without tools finishes the turn",
	"webchat.max_tokens":                             "Upper clamp on max_tokens per model call in a chat turn; a request may ask for less but never more",
	"webchat.completion_budget":                      "Caps total completion tokens summed across all iterations of one chat turn",
	"webchat.tool_result_max_chars":                  "Truncation length for a single tool result in characters; longer blocks stay readable via ctx_get offset paging",
	"webchat.history_budget_chars":                   "Character budget for session history fed into the prompt; older tool results are condensed first, then oldest messages drop",
	"webchat.llm_timeout":                            "Timeout in seconds for one model call within a chat turn; sized for slow CPU-fallback backends",
	"webchat.concurrent_turns":                       "Maximum simultaneously running chat turns per tenant home scope; above it new turns are rejected with 429 before streaming",
	"webchat.session_retention":                      "Age after which idle chat sessions and their messages are deleted (hours, suffixes h/d/w/m/y); 0 keeps them forever",
	"writes.confirm_ttl":                             "Seconds a staged LLM-path write stays confirmable before it expires; 0 lets staged writes wait forever",
	"writes.confirm_retention":                       "Age (h/d/w/m/y suffix) after which staged-write history is chunk-dropped; 0 keeps it forever — keep well above the confirm TTL",
	"pool.default_query_sensitivity":                 "Sensitivity assumed for query text without an explicit classification; decides which backend trust tiers may receive the prompt",
	"pool.default_block_sensitivity":                 "Sensitivity assigned to new blocks without an explicit classification; decides which backend trust tiers may ever see them",
	"pool.scope_sensitivity_floor":                   "JSON map of scope to minimum sensitivity; raises the effective sensitivity of blocks in that scope, never lowers it",
	"pool.llm_audit_min_sensitivity":                 "Floor under the LLM audit's sensitivity verdict; the classification may rate a block higher than this but never lower",
	"pool.blob_rate_limit_write":                     "Maximum blob uploads per API key per 60-second window; 0 falls back to the block write limit rather than unlimited",
	"pool.blob_stage_max_bytes":                      "Largest decoded payload a confirm_writes key may have staged on the MCP blob_store tool; a bigger one is refused by name instead of written direct, and 0 disables blob staging for such keys entirely",
	"pool.blob_scan_max_bytes":                       "Largest decoded blob payload the credentials detector reads on the blob write path; a bigger one is stored as metadata.sensitivity='unscanned' rather than refused, and 0 turns the scan off entirely",
	"pool.external_num_ctx_fallback":                 "Assumed context window in tokens for external backends that declare none; 0 means prompts carrying foreign text are refused",
	"pool.openrouter_window_ttl":                     "Cache lifetime in seconds for OpenRouter per-provider context-window discovery; 0 turns discovery off",
	"tenant.allow_shared_secrets":                    "Operator-set per-tenant opt-in letting secret refs fall back to shared _global provider keys; false keeps strict isolation",
	"tenant.allow_cross_tenant_block_grant":          "Operator-set per-tenant opt-in allowing single-block read grants to a foreign tenant; false limits grants to intra-tenant",
	"tenant.devmode":                                 "Developer-transparency umbrella for one tenant: false (default) seals credentials-class LLM prompt/reply bodies at write time, true stores and shows this tenant's own bodies on the status page; never widens what the tenant sees of other tenants",
	"dispatch.enabled":                               "Emergency stop for the admission dispatcher; false degrades every acquire to a pass-through with no queueing or preemption",
	"dispatch.background_queue_max":                  "Caps waiting background acquires per target; above it acquires fail fast and the job retries on its own back-off cadence",
	"dispatch.interactive_queue_per_principal":       "Caps waiting interactive acquires per API key per target; 0 disables this per-key brake",
	"dispatch.interactive_queue_per_tenant":          "Caps waiting interactive acquires per tenant per target, so minting extra keys cannot multiply the per-key cap; 0 = off",
	"dispatch.interactive_queue_max":                 "Aggregate cap on waiting interactive acquires per target; above it requests get an early 429 instead of an unservable wait; 0 = off",
	"dispatch.lease_reap_grace":                      "Slack in seconds past a lease's deadline before the reaper force-releases a never-released lease",
	"dispatch.lease_max_age":                         "Seconds after which a lease without any deadline hint is force-released; default matches the longest legitimate hold",
	"dispatch.preempt_release_timeout":               "Seconds a preempted background job may take to release its slot after cancellation before the watchdog force-releases it",
	"dispatch.background_aging_after":                "Wait in seconds before a background acquire may break interactive priority once; it never overtakes waiting interactive work, 0 = off",
	"contract.mode":                                  "Schema-contract check level (off, warn, enforce); enforcement resolves env-over-DB, so an operator env override always wins",
	"contract.recheck_interval":                      "Seconds between periodic schema-drift re-checks; 0 runs no checks while the ticker keeps polling so a later hot enable takes effect",
	"status.channel_probe_interval":                  "Seconds between latency probes of the four retrieval channels (semantic, fts_de, fts_en, trigram); 0 (default) disables the probe",
	"embed_backfill.sync_cap":                        "Maximum pending blocks a query embeds inline before its search runs; 0 = uncapped, the cap bounds first-query latency after a backlog",
	"embed_backfill.max_tokens":                      "Estimated-token threshold (length/4) above which a block is permanently parked as oversize without a wire call; 0 disables the pre-check",
	"embed_backfill.backoff_base":                    "Base delay in seconds of the exponential retry curve (base * 2^(attempts-1)) for transient embed failures. Must be > 0 (V21) — 0 would mean retry immediately, a tight loop against a failing embed backend",
	"embed_backfill.backoff_cap":                     "Upper bound in seconds on the embed-failure retry delay; a persistently failing block retries at most this often",
	"embed_migration.batch_per_cycle":                "Blocks one scheduler tick re-embeds during a migration; <=0 pauses the arm, larger batches hold the scheduler loop longer per tick",
	"embed_migration.max_tokens":                     "Oversize-gate token estimate threshold for the migration worker; larger blocks are parked without a wire call, 0 disables the pre-check",
	"embed_migration.backoff_base":                   "Base delay in seconds of the exponential retry curve for migration-scoped embed failures. Must be > 0 (V21) — 0 would mean retry immediately, a tight loop against a failing embed backend",
	"embed_migration.backoff_cap":                    "Upper bound in seconds on the retry delay for migration-scoped embed failures",
	"embed_migration.verify_sample_n":                "Sample size of the verify gate's cosine-distribution reservoir and cap on its named skip lists; <=0 skips that guard stage",
	"embed_migration.verify_overlap_k":               "k for the verify gate's Overlap@k quality metric comparing old-space vs new-space nearest neighbors",
	"embed_migration.verify_overlap_samples":         "Number of sample queries (blocks-as-queries) drawn for the Overlap@k verify stage; <=0 skips the stage",
	"recall_check.enabled":                           "Master gate for the periodic ANN-vs-exact recall measurement over the shared HNSW index; on by default so drift is measured",
	"recall_check.interval":                          "Seconds between runs of the cheap strata (small/medium scopes) of the recall measurement, hot-reloaded each iteration",
	"recall_check.offpeak_hour":                      "Local wall-clock hour anchoring the expensive strata (large/all) runs; default 4 is offset from the 03:00 daily synthesis",
	"recall_check.k_list":                            "Comma-separated result depths k at which recall is measured (10 = R@10 history, 75 = the productive semantic-CTE window)",
	"recall_check.queries_per_stratum":               "Target number of sampled queries per corpus-size stratum per run; the time and touch budgets may cut the sample short",
	"recall_check.strata_bounds":                     "Comma pair b1,b2 splitting scopes into small/medium/large by embedded active blocks; pinned to the selector dispatch thresholds",
	"recall_check.exact_budget_ms":                   "Milliseconds allowed for all exact legs of one run combined, including the stratification count and the log-sampling scan",
	"recall_check.exact_touch_budget_bytes":          "Cap on heap+TOAST bytes the exact legs may read per run; 0 resolves at runtime to 25% of shared_buffers",
	"recall_check.leg_timeout_ms":                    "Hard statement-timeout ceiling for one measurement leg so a single huge scope cannot consume the remaining run budget",
	"recall_check.park_max_ms":                       "Maximum milliseconds a run may wait parked for live query demand to pass; beyond it the run aborts as demand_deferred",
	"recall_check.ef_search":                         "hnsw.ef_search used by the ANN legs; 0 keeps the pgvector default (40), non-zero enables live tuning probes without a deploy",
	"recall_check.epsilon":                           "Distance tie tolerance of the recall definition (hit if distance <= reference distance + epsilon), stamped into each run's metadata",
	"recall_check.retention_days":                    "Days the janitor keeps recall measurement runs before deleting them from context_recall_runs",
	"retrieval.selector.enabled":                     "Turns on the strategy selector that picks exact vs ANN vector search per query from scope-size estimates; off keeps the plain ANN path",
	"retrieval.selector.exact_max":                   "Scope row count (probe-measured, clamped) up to which the vector leg runs an exact scan instead of ANN; also caps the counting probe",
	"retrieval.selector.grey_max":                    "pg_stats row-estimate ceiling of the grey zone; estimates up to it run ANN with a scan-tuple cap, larger scopes run unbounded ANN",
	"retrieval.selector.grey_scan_tuples":            "hnsw.max_scan_tuples applied in the grey zone (clamped), bounding how many tuples one ANN scan may visit",
	"retrieval.selector.stats_ttl":                   "Seconds the cached pg_stats scope-frequency snapshot is reused before refresh; non-positive falls back to 60",
	"distill.enabled":                                "Master gate of the distiller arm that turns archived agent tool output into insight blocks; off by default and a disabled arm writes no journal row at all",
	"distill.source_path":                            "Filesystem path of the read-only agent state database the arm reads; empty (the default) means no source is configured and the arm stays inert",
	"distill.source_label":                           "Stable name of the source in the run journal and in the derived watermark; renaming it restarts every session of that source at initial_backfill_rows",
	"distill.ctx_enabled":                            "Master gate of the ctx-checkpoint source, the arm's second source: the compaction checkpoints this store writes about its own sessions; off by default like the arm itself",
	"distill.ctx_source_label":                       "Stable name of the ctx-checkpoint source in the run journal and in its watermark; it must differ from source_label, or the two sources would share one watermark series and skip the ranges in between",
	"distill.ctx_quiet_for":                          "Seconds the youngest checkpoint of a root session must have been quiet before that session is distilled; the counterpart of session_quiet_for for the ctx source, set above the measured 11-minute median compaction distance",
	"distill.ctx_session_horizon":                    "Seconds of activity window the ctx source's candidate list is capped to; it keeps the one corpus-scaling query of that source off a full scan, and a root outside the window only leaves the candidate list — reading it still works. 0 means no cap",
	"distill.interval":                               "Seconds between distiller ticks; deliberately not anchored to a wall-clock hour so insights reach the corpus while the session they came from is still relevant",
	"distill.session_quiet_for":                      "Seconds a session must have been quiet before it is distilled, measuring the foreign runtime's live load at its source; 0 turns the gate off (snapshot access mode)",
	"distill.max_sessions_per_run":                   "Maximum sources one tick may touch, the rest rotating round-robin; this bounds the read order, not the call budget",
	"distill.concurrency":                            "How many source sessions of one tick run at the same time; 1 (the default) is the strictly sequential arm, and inside a single source the arm stays sequential at every setting, because only a complete batch prefix may move that source's watermark. Raising it is a statement about the serving side, and it lets up to concurrency-1 calls be paid for before either spend ceiling can see them",
	"distill.rows_per_read":                          "Mandatory LIMIT on every read of the foreign database; the foreign schema guarantees no index, so an unbounded read would scan a multi-gigabyte file",
	"distill.min_row_runes":                          "Rune length below which a tool row is dropped as substanceless before it costs anything (exit codes, ok, empty answers)",
	"distill.max_row_runes":                          "Head cap in runes per tool row kept for the prompt; together with rows_per_call it must fit the BudgetDistill prompt budget or the write is rejected",
	"distill.rows_per_call":                          "Upper bound of tool rows per LLM call; the prompt assembler cuts earlier for unusually long rows, whichever hits first",
	"distill.dryrun_dir":                             "Directory the dry-run dump of the selected chunks is written to, one file per run, mode 0700. It must be an absolute path OUTSIDE every git working copy — the dump carries raw session prose, and a working copy is a push away from publishing it. Empty turns the plaintext dump off and leaves only the counted figures and the chunk hashes in the journal",
	"distill.initial_backfill_rows":                  "How many archived rows of a session below its head a first run starts at; 0 (the default) starts at the head and ignores the backlog. Counts rows, never id deltas",
	"distill.local_only":                             "Keeps the distill call on local and LAN backends regardless of trust; covers the call only, never the block's later life cycle (see block_sensitivity)",
	"distill.call_timeout":                           "Seconds one distill call may take; a timeouts entry on the serving backend row takes precedence",
	"distill.num_predict":                            "Answer budget of one distill call in tokens; a cost policy rather than a safety floor, sized for four to six insights with their quotes",
	"distill.scope":                                  "Target scope of the insight blocks; empty inherits scheduler.home_scope like every other arm, and shared is refused with 422 as a cross-tenant propagation path",
	"distill.category":                               "Block category the insights are written to; it is half of the upsert identity, so changing it starts a new series instead of rewriting the old one",
	"distill.block_type":                             "Block type every insight block is written under; it must name a compiled type that neither guards nor is fully retrievable, and only the derived layer's own types may be retrieval-excluded",
	"distill.checkpoint_category":                    "Category the arm searches for the checkpoint manifest it links its blocks to; no hit is not an error, the block is written without the link",
	"distill.max_block_runes":                        "Rune cap of one insight block; above the zettelkasten doctrine on purpose because an insight block is an evidence collection, not one concept",
	"distill.max_blocks_per_root":                    "How many insight blocks one range of a root session may grow to before the arm stops opening new shards; it answers skipped/budget when it binds at run start and partial/budget when it binds mid-run, holding the material back rather than dropping it, and a range held that way waits until the cap is raised; 0 is the documented no-cap default and never means \"no blocks\", and a cap that is meant never to bind sits far above the 6-9 shards a range is expected to need",
	"distill.block_sensitivity":                      "Sensitivity stamped on every insight block and the only lever over which backends may ever see it; hard floor internal, public is refused with 422",
	"distill.novelty_floor":                          "Minimum share of a claim's tokens that must NOT stand in the quote it cites; a claim below it is discarded instead of written and counted in distill_run.rej_novelty, which is what stops verbatim quote copies that every evidence gate passes; 0 switches the floor off, values above 1 are refused",
	"distill.spend_window":                           "Seconds of the sliding window the call budget is counted in, durably over the LLM log so a restart loop cannot blind the guard",
	"distill.spend_max_calls":                        "Maximum distill calls inside one spend window before a source trips into back-off; 0 is the documented kill switch that disables the guard",
	"distill.spend_max_gpu_seconds":                  "GPU seconds the distiller may consume inside one spend window, summed over the LLM log's duration; the axis that actually binds, because the call ceiling counts a ten-times more expensive answer as one call too, and 0 is the kill switch of this axis alone",
	"distill.spend_backoff":                          "Seconds a source rests after tripping the call budget; the watermark stays put, so the skipped range is postponed rather than lost",
	"distill.breaker_failures":                       "Consecutive failures that open the per-backend circuit breaker; must be at least 1, since 0 would open it before any failure",
	"distill.breaker_cooldown":                       "Seconds an open breaker rests; one full interval means the next tick is skipped and the one after it is a real attempt",
	"distill.retention_days":                         "Days the janitor keeps distiller run journal rows; 0 keeps them forever",
	"distill.seen_retention_days":                    "Days the janitor keeps cross-run dedup hashes; shorter than the journal because a hash only helps while the same output keeps recurring, 0 keeps them forever",
}
