package blocktype

import "testing"

// T4 classification golden corpus (design/01 §7-T4 gate).
//
// The expected values were GENERATED by running the pre-T4 code state
// (store.ClassifyBlockAfterUpsert decision tree + rrf.HasAuditTrailIntent,
// commit 0352d9d) over these input triples BEFORE the tree was replaced —
// they are the frozen contract, not a re-derivation from the new engine.
// wantRole "" means the old tree did NOT classify (block keeps the default
// type) and maps to matched=false here.
//
// Notable pinned edges:
//   - source-dream-exact: source == bare prefix "dream-" never matched
//     (old: len(src) > 6) — Set.Classify requires a PROPER prefix.
//   - source-dream-upper: source matching is case-SENSITIVE.
//   - title matching is case-INSENSITIVE substring (rrf.MatchesAny).
//   - nomatch-partial-pattern "Wellenreiten in Portugal" DOES match
//     ("welle" substring) — a known old-tree false positive, kept.
func TestClassifyGoldenAgainstOldTree(t *testing.T) {
	s := builtinTestSet(t)

	cases := []struct {
		name     string
		title    string
		metadata map[string]any
		wantRole string // "" = old tree returned no classification
	}{
		// -- branch 1: metadata is_meta flag --
		{"meta-flag-true", "Some Block", map[string]any{"is_meta": true}, "system-meta"},
		{"meta-flag-false", "Some Block", map[string]any{"is_meta": false}, ""},
		{"meta-flag-string", "Some Block", map[string]any{"is_meta": "true"}, ""},
		{"meta-flag-absent", "Plain Block", map[string]any{}, ""},
		{"meta-flag-nil-map", "Plain Block", nil, ""},
		{"meta-flag-wins-over-source", "Some Block", map[string]any{"is_meta": true, "source": "dream-synthesis"}, "system-meta"},
		{"meta-flag-wins-over-title", "Session 7 Handover", map[string]any{"is_meta": true}, "system-meta"},
		// -- branch 2: dream- source prefix --
		{"source-dream-synthesis", "Tagesbericht 2026-05-07", map[string]any{"source": "dream-synthesis"}, "audit-trail"},
		{"source-dream-x", "Irgendwas", map[string]any{"source": "dream-x"}, "audit-trail"},
		{"source-dream-exact", "Irgendwas", map[string]any{"source": "dream-"}, ""},
		{"source-dream-no-dash", "Irgendwas", map[string]any{"source": "dreamer"}, ""},
		{"source-dream-upper", "Irgendwas", map[string]any{"source": "Dream-synthesis"}, ""},
		{"source-claude-code", "ddstatus mariadb donnerstags", map[string]any{"source": "claude-code-2026-05-07"}, ""},
		{"source-empty", "Unrelated", map[string]any{"source": ""}, ""},
		{"source-nonstring", "Unrelated", map[string]any{"source": 42}, ""},
		{"source-wins-over-title", "Session 7 Handover", map[string]any{"source": "dream-daily"}, "audit-trail"},
		// -- branch 3: title patterns (all 10, mixed casing/embedding) --
		{"title-session", "Session 7 Abschlussbilanz", map[string]any{}, "audit-trail"},
		{"title-session-upper", "SESSION 12 RETRO", map[string]any{}, "audit-trail"},
		{"title-session-embedded", "Multisession-Auswertung", map[string]any{}, "audit-trail"},
		{"title-welle", "Welle 42 Bench-Verdict", map[string]any{}, "audit-trail"},
		{"title-welle-lower", "kleine welle im teich", map[string]any{}, "audit-trail"},
		{"title-audit", "Audit der Zugriffe", map[string]any{}, "audit-trail"},
		{"title-audit-embedded", "Selbstauditierung Q3", map[string]any{}, "audit-trail"},
		{"title-recurrent", "Recurrent Pattern Analyse", map[string]any{}, "audit-trail"},
		{"title-handover", "Handover an Session-Nachfolger", map[string]any{}, "audit-trail"},
		{"title-self-audit", "Self-Audit 2026-06", map[string]any{}, "audit-trail"},
		{"title-self-audit-upper", "SELF-AUDIT Bericht", map[string]any{}, "audit-trail"},
		{"title-dream-v", "Dream v3 Qualitäts-Messung", map[string]any{}, "audit-trail"},
		{"title-dream-v-nospace", "Dreamv3 Messung", map[string]any{}, ""},
		{"title-performance", "Performance-Messung Embed-Cache", map[string]any{}, "audit-trail"},
		{"title-reset", "Baseline nach Reset", map[string]any{}, "audit-trail"},
		{"title-reset-only", "Resetverhalten PG18", map[string]any{}, "audit-trail"},
		{"title-baseline", "Neue Baseline gesetzt", map[string]any{}, "audit-trail"},
		{"title-umlaut", "Selbstprüfung ohne Schlüsselwort", map[string]any{}, ""},
		// -- no-match corpus --
		{"nomatch-generic", "PostgreSQL Tuning Cheatsheet", map[string]any{}, ""},
		{"nomatch-config", "llama.cpp Engine-Konfiguration", map[string]any{"source": "claude-code-2026-06-01"}, ""},
		{"nomatch-partial-pattern", "Wellenreiten in Portugal", map[string]any{}, "audit-trail"},
		{"nomatch-empty-title", "", map[string]any{}, ""},
		{"nomatch-tags-only", "Obsidian Vault Sync", map[string]any{"tags": []string{"session"}}, ""},
		// -- combos --
		{"combo-source+title", "Welle 9 Handover", map[string]any{"source": "dream-link"}, "audit-trail"},
		{"combo-false-meta+dream", "Unrelated", map[string]any{"is_meta": false, "source": "dream-daily"}, "audit-trail"},
		{"combo-false-meta+title", "Session Recap", map[string]any{"is_meta": false}, "audit-trail"},
	}

	for _, tc := range cases {
		t.Run(tc.name, func(t *testing.T) {
			got, matched := s.Classify(tc.title, tc.metadata)
			if tc.wantRole == "" {
				if matched {
					t.Errorf("Classify(%q, %v) = (%q, true), old tree did NOT classify", tc.title, tc.metadata, got)
				}
				if got != "knowledge" {
					t.Errorf("no-match default = %q, want knowledge", got)
				}
				return
			}
			if !matched || got != tc.wantRole {
				t.Errorf("Classify(%q, %v) = (%q, %v), old tree => %q", tc.title, tc.metadata, got, matched, tc.wantRole)
			}
		})
	}
}
