//go:build integration

package store_test

import (
	"context"
	"testing"
	"time"

	"github.com/jackc/pgx/v5/pgxpool"

	"github.com/GottZ/ctx/internal/store"
	"github.com/GottZ/ctx/internal/testdb"
)

// TestClassifyBlockAfterUpsert_Decisions verifies the four-branch decision
// tree of store.ClassifyBlockAfterUpsert.
func TestClassifyBlockAfterUpsert_Decisions(t *testing.T) {
	pool := testdb.SetupTestDB(t)
	ctx := context.Background()

	cases := []struct {
		name       string
		title      string
		metadata   map[string]any
		wantRole   string
		wantIsMeta bool
	}{
		{
			name:       "metadata-is-meta-flag",
			title:      "Some Block",
			metadata:   map[string]any{"is_meta": true},
			wantRole:   "system-meta",
			wantIsMeta: true,
		},
		{
			name:       "metadata-dream-source",
			title:      "Tagesbericht 2026-05-07",
			metadata:   map[string]any{"source": "dream-synthesis"},
			wantRole:   "audit-trail",
			wantIsMeta: false,
		},
		{
			name:       "title-pattern-session",
			title:      "Session 7 Abschlussbilanz",
			metadata:   map[string]any{},
			wantRole:   "audit-trail",
			wantIsMeta: false,
		},
		{
			name:       "title-pattern-welle",
			title:      "Welle 42 Bench-Verdict",
			metadata:   nil,
			wantRole:   "audit-trail",
			wantIsMeta: false,
		},
		{
			name:       "no-pattern-no-meta-noop",
			title:      "ddstatus mariadb donnerstags",
			metadata:   map[string]any{"source": "claude-code-2026-05-07"},
			wantRole:   "", // no UPDATE — defaults stay
			wantIsMeta: false,
		},
	}

	for _, tc := range cases {
		t.Run(tc.name, func(t *testing.T) {
			id := insertClassifyTestBlock(t, pool, tc.title)
			role, isMeta, err := store.ClassifyBlockAfterUpsert(ctx, pool, id, tc.title, tc.metadata)
			if err != nil {
				t.Fatalf("ClassifyBlockAfterUpsert: %v", err)
			}
			if role != tc.wantRole {
				t.Errorf("role = %q, want %q", role, tc.wantRole)
			}
			if isMeta != tc.wantIsMeta {
				t.Errorf("isMeta = %v, want %v", isMeta, tc.wantIsMeta)
			}

			// Verify DB state matches return values (or default state for noop).
			var dbRole string
			var dbIsMeta bool
			err = pool.QueryRow(ctx,
				`SELECT block_role, is_meta FROM context_blocks WHERE id = $1::uuid`, id,
			).Scan(&dbRole, &dbIsMeta)
			if err != nil {
				t.Fatalf("verify DB: %v", err)
			}
			expectRole := tc.wantRole
			if expectRole == "" {
				expectRole = "knowledge"
			}
			if dbRole != expectRole {
				t.Errorf("DB block_role = %q, want %q", dbRole, expectRole)
			}
			if dbIsMeta != tc.wantIsMeta {
				t.Errorf("DB is_meta = %v, want %v", dbIsMeta, tc.wantIsMeta)
			}
		})
	}
}

// insertClassifyTestBlock inserts a minimal context_blocks row and returns
// its id. UUID is auto-generated by uuidv7() default.
func insertClassifyTestBlock(t *testing.T, pool *pgxpool.Pool, title string) string {
	t.Helper()
	now := time.Now().UTC()
	var id string
	err := pool.QueryRow(context.Background(),
		`INSERT INTO context_blocks (category, title, content, scope, created_at, updated_at)
		 VALUES ($1, $2, $3, 'private', $4, $4)
		 RETURNING id::text`,
		"test_classify", title, "classify-test-content", now,
	).Scan(&id)
	if err != nil {
		t.Fatalf("insert classify-test block: %v", err)
	}
	return id
}
