package schemacontract

import (
	_ "embed"
	"encoding/json"
	"fmt"
)

// manifest.json is generated by TestGenerateManifest (-tags=genmanifest,
// design/03 §4.9) against a fresh migration chain on the prod-parity
// Postgres image, and checked into the repo. It is embedded — not read from
// disk at runtime — so the vertrag ships inside the same binary as the
// migrations that define it (design/03 §3.2: "der Vertrag muss außerhalb
// des Prüflings leben"). The pre-commit hook (.hooks/pre-commit) blocks a
// staged migration without a staged manifest regeneration alongside it.
//
//go:embed manifest.json
var manifestJSON []byte

var embeddedManifest Manifest

func init() {
	m, err := ParseManifest(manifestJSON)
	if err != nil {
		panic(fmt.Sprintf("schemacontract: embedded manifest.json invalid: %v", err))
	}
	embeddedManifest = m
}

// Embedded returns the generated, go:embed-loaded Manifest. Check uses this
// internally; it is exported so callers that only need the static
// expectation (without running Check against a DB) can read it too.
func Embedded() Manifest {
	return embeddedManifest
}

// ParseManifest decodes a manifest.json payload. Exported so the generator
// (-tags=genmanifest) and tests can round-trip a Manifest without each
// re-deriving the JSON shape.
func ParseManifest(data []byte) (Manifest, error) {
	var m Manifest
	if err := json.Unmarshal(data, &m); err != nil {
		return Manifest{}, fmt.Errorf("unmarshal manifest: %w", err)
	}
	return m, nil
}

// MarshalManifest renders m as deterministic, diffable JSON: encoding/json
// already sorts map[string]T keys alphabetically, so the only extra
// discipline the generator owes is sorting slice fields (Hypertables,
// GucProbes) before calling this — MarshalManifest itself adds nothing but
// the indent width and a trailing newline, so two generator runs against an
// unchanged catalog produce byte-identical output (design/03 §4.9 gate 4).
func MarshalManifest(m Manifest) ([]byte, error) {
	b, err := json.MarshalIndent(m, "", "  ")
	if err != nil {
		return nil, fmt.Errorf("marshal manifest: %w", err)
	}
	return append(b, '\n'), nil
}
